const $=s=>document.querySelector(s);let events=[],category='Todo';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function validUrl(s){try{const u=new URL(s);return u.protocol==='https:'?u.href:''}catch{return ''}}
function match(e){const q=$('#search').value.toLocaleLowerCase('es');const text=(e.title+' '+e.venue+' '+e.category).toLocaleLowerCase('es');if(!text.includes(q)||category!=='Todo'&&e.category!==category||$('#free').checked&&!e.free)return false;const mode=$('#date').value;if(mode==='all')return true;const now=new Date();const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Tijuana',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);const end=e.endDate||e.date;if(end<today)return false;if(mode==='upcoming')return true;if(mode==='month')return e.date.slice(0,7)===today.slice(0,7)||e.date<today&&end>=today;const seven=new Date(today+'T12:00:00Z');seven.setUTCDate(seven.getUTCDate()+7);return e.date<=seven.toISOString().slice(0,10);}
function render(){const list=events.filter(match);$('#count').textContent=String(list.length).padStart(2,'0');$('#cards').innerHTML=list.length?list.map((e,i)=>`<article class="event-card ${escape(e.tone)} ${i===0?'lead':''}"><button class="card-button" data-id="${escape(e.id)}" aria-label="Ver ${escape(e.title)}"><div class="card-visual">${validUrl(e.image)?`<img src="${escape(validUrl(e.image))}" alt="${escape(e.title)}" loading="${i===0?'eager':'lazy'}">`:`<div class="typographic">HAZ<br>ALGO<span>↗</span></div>`}<span class="category-label">${escape(e.category)}</span><span class="date-badge">${escape(e.dateLabel)}</span></div><div class="card-body"><h3>${escape(e.title)} <span>↗</span></h3><p>${escape(e.venue)}</p><div class="card-bottom"><span class="${e.free?'free':''}">${escape(e.price)}</span><span>Ver plan →</span></div></div></button></article>`).join(''):'<div class="empty"><h3>No encontramos ese plan.</h3><p>Prueba otra categoría o cambia la búsqueda.</p><button id="reset" class="primary">Mostrar todos</button></div>';document.querySelectorAll('.card-visual img').forEach(img=>img.addEventListener('error',()=>{img.hidden=true;},{once:true}));document.querySelectorAll('[data-id]').forEach(b=>b.addEventListener('click',()=>detail(events.find(e=>e.id===b.dataset.id))));$('#reset')?.addEventListener('click',()=>{$('#search').value='';$('#free').checked=false;$('#date').value='all';choose('Todo');});}
function choose(value){category=value;document.querySelectorAll('[data-category]').forEach(b=>{b.classList.toggle('selected',b.dataset.category===value);b.setAttribute('aria-pressed',String(b.dataset.category===value));});render();}
function detail(e){$('#detail-content').innerHTML=`<div class="eyebrow">${escape(e.category)} · ${escape(e.dateLabel)}</div><h2>${escape(e.title)}</h2><p class="venue">${escape(e.venue)}</p><p>${escape(e.description)}</p><div class="detail-price">${escape(e.price)}</div><a class="primary" href="${escape(validUrl(e.source))}" target="_blank" rel="noopener noreferrer">Consultar fuente oficial ↗</a><p class="fine">Esta cartelera no vende entradas para este evento. Información revisada el 5 de septiembre de 2026; confirma disponibilidad con el organizador.</p>`;$('#detail').showModal();}
document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>choose(b.dataset.category)));$('#search').addEventListener('input',render);$('#free').addEventListener('change',render);$('#date').addEventListener('change',render);$('.close').addEventListener('click',()=>$('#detail').close());$('#detail').addEventListener('click',e=>{if(e.target===$('#detail'))$('#detail').close();});
try{const r=await fetch('events.json');if(!r.ok)throw Error();events=await r.json();render();}catch{$('#cards').innerHTML='<div class="empty"><h3>No pudimos cargar los eventos.</h3><p>Recarga la página para volver a intentarlo.</p></div>';}

