import {filterEvents,localToday,occurs,nextDate} from './catalog.mjs';
const $=s=>document.querySelector(s);let events=[],category='Todo',chosenDay='',calendar=false;const today=localToday();let month=today.slice(0,7);
const escape=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function validUrl(s){try{const u=new URL(s);return u.protocol==='https:'?u.href:''}catch{return ''}}
function options(){return {q:$('#search').value,category,venue:$('#venue').value,date:$('#date').value,free:$('#free').checked,budget:$('#budget').value,day:chosenDay,today};}
function render(){const list=filterEvents(events,options());$('#count').textContent=String(list.length).padStart(2,'0');$('#selection').textContent=chosenDay?'Actividades del '+new Date(chosenDay+'T12:00:00').toLocaleDateString('es-MX',{day:'numeric',month:'long'})+' · Usa Limpiar filtros para volver a toda la agenda.':'';$('#cards').innerHTML=list.length?list.map(e=>`<article class="event-card ${escape(e.tone)}"><a class="card-button" href="eventos/${encodeURIComponent(e.id)}.html"><div class="card-visual">${validUrl(e.image)?`<img src="${escape(validUrl(e.image))}" alt="${escape(e.title)}" loading="lazy">`:`<div class="typographic">${escape(e.category)}<br>en Tijuana ↗</div>`}<span class="category-label">${escape(e.category)}</span><span class="date-badge">${escape(e.dateLabel)}</span></div><div class="card-body"><h3>${escape(e.title)} <span>↗</span></h3><p>${escape(e.venue)}</p><div class="card-bottom"><span class="${e.free?'free':''}">${escape(e.price)}</span><span>${escape(e.time||'Ver horarios')} →</span></div></div></a></article>`).join(''):'<div class="empty"><h3>No encontramos ese plan.</h3><p>Prueba otra fecha o elimina algún filtro.</p><button id="reset" class="primary">Limpiar filtros</button></div>';document.querySelectorAll('.card-visual img').forEach(img=>img.addEventListener('error',()=>{img.hidden=true;},{once:true}));$('#reset')?.addEventListener('click',reset);if(calendar)renderCalendar();const p=new URLSearchParams();const o=options();for(const k of ['q','category','venue','date','budget','day'])if(o[k]&&o[k]!=='Todo'&&o[k]!=='upcoming')p.set(k,o[k]);if(o.free)p.set('free','1');history.replaceState(null,'',location.pathname+(p.size?'?'+p:'')+'#eventos');}
function choose(value){category=value;document.querySelectorAll('[data-category]').forEach(b=>{b.classList.toggle('selected',b.dataset.category===value);b.setAttribute('aria-pressed',String(b.dataset.category===value));});render();}
function reset(){for(const k of ['search','venue','budget'])$('#'+k).value='';$('#free').checked=false;$('#date').value='upcoming';chosenDay='';choose('Todo');}
function renderCalendar(){const start=new Date(month+'-01T12:00:00Z');$('#month-title').textContent=start.toLocaleDateString('es-MX',{month:'long',year:'numeric',timeZone:'UTC'});const offset=(start.getUTCDay()+6)%7;const days=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+1,0)).getUTCDate();const pool=filterEvents(events,{...options(),date:'all',day:''});let html=['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(s=>'<div class="weekday">'+s+'</div>').join('');for(let i=0;i<offset;i++)html+='<div class="calendar-day empty-day" aria-hidden="true"></div>';for(let i=1;i<=days;i++){const day=month+'-'+String(i).padStart(2,'0');const count=pool.filter(e=>occurs(e,day)).length;html+=`<button class="calendar-day ${day===chosenDay?'chosen':''} ${day===today?'today':''}" data-day="${day}" aria-label="${day}: ${count} eventos" aria-pressed="${day===chosenDay}">${i}${count?`<span>${count} ${count===1?'plan':'planes'}</span>`:''}</button>`;}$('#calendar-grid').innerHTML=html;document.querySelectorAll('[data-day]').forEach(b=>b.addEventListener('click',()=>{chosenDay=b.dataset.day;render();}));}
function setView(value){calendar=value;$('#agenda').hidden=!value;$('#grid-view').classList.toggle('selected',!value);$('#calendar-view').classList.toggle('selected',value);$('#grid-view').setAttribute('aria-pressed',String(!value));$('#calendar-view').setAttribute('aria-pressed',String(value));if(value)renderCalendar();}
document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>choose(b.dataset.category)));$('#search').addEventListener('input',render);for(const k of ['free','venue','budget'])$('#'+k).addEventListener('change',render);$('#date').addEventListener('change',()=>{chosenDay='';render();});$('#clear').addEventListener('click',reset);$('#grid-view').addEventListener('click',()=>setView(false));$('#calendar-view').addEventListener('click',()=>setView(true));$('#calendar-nav').addEventListener('click',()=>setView(true));for(const [id,n] of [['prev-month',-1],['next-month',1]])$('#'+id).addEventListener('click',()=>{const d=new Date(month+'-01T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+n);month=d.toISOString().slice(0,7);renderCalendar();});
try{const r=await fetch('events.json');if(!r.ok)throw Error();events=await r.json();$('#venue').innerHTML='<option value="">Todos los lugares</option>'+[...new Set(events.map(e=>e.venue))].sort().map(v=>`<option value="${escape(v)}">${escape(v)}</option>`).join('');const p=new URLSearchParams(location.search);for(const [key,id] of [['q','search'],['venue','venue'],['date','date'],['budget','budget']])if(p.has(key))$('#'+id).value=p.get(key);$('#free').checked=p.get('free')==='1';if(/^\d{4}-\d{2}-\d{2}$/.test(p.get('day')||''))chosenDay=p.get('day');choose(p.get('category')||'Todo');}catch{$('#cards').innerHTML='<div class="empty"><h3>No pudimos cargar los eventos.</h3><p>Recarga la página para volver a intentarlo.</p></div>';}
