const $=s=>document.querySelector(s);const fields=['source','title','event-date','time','category','price','venue','description'];let network='Instagram',current=null,objectUrl=null,dirty=false;
function data(){return Object.fromEntries(fields.map(f=>[f,$('#'+f).value.trim()]));}
function validate(){if(!$('#event-form').reportValidity())return false;try{if(!['https:','http:'].includes(new URL($('#source').value).protocol))throw Error();}catch{$('#form-status').textContent='Usa un enlace web válido.';return false;}return true;}
function render(){if(!current)return;const d=current;const date=d['event-date']?new Date(d['event-date']+'T12:00:00').toLocaleDateString('es-MX',{day:'numeric',month:'long',year:'numeric'}):'Fecha por confirmar';const when=date+(d.time?' · '+d.time:'');const price=d.price||'Precio por confirmar';const base=d.title+'\n\n'+d.description+'\n\n📅 '+when+'\n📍 '+d.venue+'\n🎟 '+price;const source='\n\nDetalles y confirmación: '+d.source;let text;if(network==='Facebook')text='¿Buscas un plan en Tijuana?\n\n'+base+source;else if(network==='TikTok')text='GUION CORTO\n\nInicio: «Un plan para salir de lo mismo en Tijuana: '+d.title+'.»\n\nDesarrollo: '+d.description+'\n\nDatos en pantalla: '+when+' · '+d.venue+' · '+price+'\n\nCierre: «Consulta los detalles con el organizador.»'+source;else if(network==='YouTube')text='TÍTULO\n'+d.title+' | Planes en Tijuana\n\nGUION\nHoy te compartimos '+d.title+'. '+d.description+'\n\nSerá el '+when+' en '+d.venue+'. '+price+'. Confirma los detalles con la fuente oficial.\n\nDESCRIPCIÓN\n'+base+source;else text=base+source+'\n\n#Tijuana #PlanesEnTijuana #MIATijuana';$('#copy').textContent=text;$('#copy-button').disabled=false;}
$('#event-form').addEventListener('submit',e=>{e.preventDefault();if(!validate())return;current=data();render();$('#form-status').textContent='Contenido preparado. Puedes cambiar de canal y copiarlo.';});
document.querySelectorAll('[data-network]').forEach(b=>b.addEventListener('click',()=>{network=b.dataset.network;document.querySelectorAll('[data-network]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});render();}));
$('#copy-button').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#copy').textContent);$('#copy-status').textContent='Texto copiado.';}catch{$('#copy-status').textContent='No se pudo copiar automáticamente. Selecciona el texto y cópialo.';}});
$('#download').addEventListener('click',()=>{if(!validate())return;const blob=new Blob([JSON.stringify({version:1,...data(),verified:true},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='mia-ficha-evento.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);dirty=false;$('#form-status').textContent='Ficha descargada. El cartel debe conservarse por separado.';});
$('#import').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>50000)throw Error();const d=JSON.parse(await file.text());if(d.version!==1||typeof d.title!=='string')throw Error();for(const key of fields)$('#'+key).value=typeof d[key]==='string'?d[key].slice(0,key==='description'?3000:500):'';$('#verified').checked=false;current=null;$('#copy-button').disabled=true;$('#copy').textContent='Revisa los datos y prepara el contenido de nuevo.';$('#form-status').textContent='Ficha recuperada. Confirma los datos antes de usarla.';dirty=true;}catch{$('#form-status').textContent='No se pudo abrir la ficha. Selecciona un archivo descargado desde este estudio.';}});
$('#poster').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>10*1024*1024){$('#form-status').textContent='Usa una imagen JPG, PNG o WebP de hasta 10 MB.';return;}if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(f);$('#poster-preview').src=objectUrl;$('#poster-preview').hidden=false;});
$('#event-form').addEventListener('input',()=>{dirty=true;if(current){current=null;$('#copy-button').disabled=true;$('#copy').textContent='La ficha cambió. Pulsa Preparar contenido para actualizar los textos.';}});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
