import {mkdir,copyFile,readFile,writeFile,readdir,unlink} from 'node:fs/promises';
const files=['index.html','styles.css','app.js','catalog.mjs','detail.js','events.json'];const origin='https://descubre-tijuana.vercel.app';
await mkdir('dist/eventos',{recursive:true});
const events=JSON.parse(await readFile('events.json','utf8'));const ids=new Set();
for(const e of events){if(!/^[a-z0-9-]+$/.test(e.id)||ids.has(e.id)||!e.title||!/^https:\/\//.test(e.source)||!/^\d{4}-\d{2}-\d{2}$/.test(e.date))throw Error('Evento inválido: '+e.id);ids.add(e.id);}
for(const f of ['estudio.html','studio.js']){try{await unlink('dist/'+f);}catch(e){if(e.code!=='ENOENT')throw e;}}
for(const f of await readdir('dist/eventos'))if(/\.(html|ics)$/.test(f)&&!ids.has(f.replace(/\.(html|ics)$/,'')))await unlink('dist/eventos/'+f);
for(const file of files)await copyFile(file,'dist/'+file);
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=d=>new Date(d+'T12:00:00Z').toLocaleDateString('es-MX',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'});
const ical=s=>String(s||'').replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');
function fold(line){let out='',part='';for(const ch of line){if(Buffer.byteLength(part+ch)>73){out+=part+'\r\n';part=' ';}part+=ch;}return out+part;}
for(const e of events){const url=origin+'/eventos/'+e.id+'.html';const sessions=e.sessions?.length?e.sessions:[{date:e.date,time:e.time}];const dates=sessions.map(s=>`<li>${esc(fmt(s.date))}${s.time?' · '+esc(s.time):' · Horario por confirmar'}</li>`).join('');const calendarEnabled=sessions.some(s=>s.time)&&!e.scheduleNote;
const schema={'@context':'https://schema.org','@type':'Event',name:e.title,startDate:e.date,...(e.endDate?{endDate:e.endDate}:{}),url,description:e.description,location:{'@type':'Place',name:e.venue,...(e.address?{address:e.address}:{})},...(e.image?{image:e.image}:{})};
const html=`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(e.title)} · Descubre Tijuana</title><meta name="description" content="${esc(e.description)}"><link rel="canonical" href="${url}"><meta property="og:title" content="${esc(e.title)}"><meta property="og:description" content="${esc(e.venue+' · '+e.dateLabel+' · '+e.price)}"><meta property="og:url" content="${url}"><link rel="stylesheet" href="../styles.css"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script></head><body><header class="top"><a class="brand" href="../index.html">descubre<span>TIJUANA<br>↗</span></a><nav><a href="../index.html#eventos">← Volver a la cartelera</a></nav></header><main class="detail-page"><div class="breadcrumbs"><a href="../index.html">Explorar</a> / ${esc(e.category)}</div><div class="eyebrow">${esc(e.category)} · ${esc(e.dateLabel)}</div><h1>${esc(e.title)}</h1><div class="detail-layout"><section>${e.image?`<img class="detail-poster" src="${esc(e.image)}" alt="${esc(e.title)}">`:''}<p class="detail-description">${esc(e.description)}</p><h2>Fechas y horarios</h2><ul class="sessions">${dates}</ul>${e.endDate&&!e.sessions?`<p>Actividad anunciada hasta el ${esc(fmt(e.endDate))}. Consulta los días y horarios de apertura con el organizador.</p>`:''}${e.scheduleNote?`<p class="notice">${esc(e.scheduleNote)}</p>`:''}<div class="detail-actions">${calendarEnabled?`<a class="secondary" href="${e.id}.ics" download>Agregar al calendario ↓</a>`:''}<button id="share" class="secondary">Copiar enlace ↗</button></div><p id="share-status" class="hint" role="status"></p></section><aside><dl class="detail-info"><dt>Lugar</dt><dd>${esc(e.venue)}</dd>${e.address?`<dt>Dirección</dt><dd>${esc(e.address)}</dd>`:''}<dt>Acceso</dt><dd>${esc(e.price)}</dd>${e.audience?`<dt>Edades</dt><dd>${esc(e.audience)}</dd>`:''}${e.organizer?`<dt>Organizador</dt><dd>${esc(e.organizer)}</dd>`:''}</dl><div class="detail-actions"><a class="primary" href="${esc(e.source)}" target="_blank" rel="noopener noreferrer">Consultar fuente oficial ↗</a><a class="secondary" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent((e.address||e.venue)+' Tijuana')}" target="_blank" rel="noopener noreferrer">Ubicación en Maps ↗</a></div><p class="detail-source">Fuente: ${esc(e.sourceName||new URL(e.source).hostname)}<br>Revisado: ${esc(fmt(e.verified))}<br>Confirma cambios, cupo y boletos con el organizador. Esta cartelera no vende entradas.</p></aside></div><section class="related"><h2>También en ${esc(e.category.toLowerCase())}</h2>${events.filter(x=>x.id!==e.id&&x.category===e.category).slice(0,3).map(x=>`<a href="${x.id}.html">${esc(x.title)} · ${esc(x.dateLabel)} ↗</a>`).join('')||'<a href="../index.html">Explorar más actividades ↗</a>'}</section></main><script src="../detail.js" type="module"></script></body></html>`;
await writeFile('dist/eventos/'+e.id+'.html',html);
if(calendarEnabled){const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Descubre Tijuana//Agenda//ES','CALSCALE:GREGORIAN','BEGIN:VTIMEZONE','TZID:America/Tijuana','BEGIN:DAYLIGHT','DTSTART:19700308T020000','RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU','TZOFFSETFROM:-0800','TZOFFSETTO:-0700','END:DAYLIGHT','BEGIN:STANDARD','DTSTART:19701101T020000','RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU','TZOFFSETFROM:-0700','TZOFFSETTO:-0800','END:STANDARD','END:VTIMEZONE'];for(const s of sessions.filter(s=>s.time))lines.push('BEGIN:VEVENT','UID:'+e.id+'-'+s.date+'@descubre-tijuana.vercel.app','DTSTAMP:'+new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,''),'DTSTART;TZID=America/Tijuana:'+s.date.replaceAll('-','')+'T'+s.time.replace(':','')+'00','SUMMARY:'+ical(e.title),'LOCATION:'+ical(e.venue),'DESCRIPTION:'+ical('Confirma cambios con la fuente oficial: '+e.source),'URL:'+url,'END:VEVENT');lines.push('END:VCALENDAR');await writeFile('dist/eventos/'+e.id+'.ics',lines.map(fold).join('\r\n')+'\r\n');}}
await writeFile('dist/robots.txt','User-agent: *\nAllow: /\nSitemap: '+origin+'/sitemap.xml\n');
await writeFile('dist/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+[origin+'/',...events.map(e=>origin+'/eventos/'+e.id+'.html')].map(url=>'<url><loc>'+url+'</loc></url>').join('')+'</urlset>');
console.log('Sitio preparado: '+events.length+' eventos con páginas individuales.');
